### ISSUE TITLE
请问脚本支持GCP的ARM机型吗？

### ISSUE THREAD

**Issue by lsyyktv** [bohanyang/debi#100]
![image](https://github.com/bohanyang/debi/assets/39065858/f845f4b5-9ce5-4e6c-a6b0-f83990925e3e)

请问脚本支持GCP的ARM机型吗？

sudo ./debi.sh --cdn --network-console --ethx   --gateway 10.0.1.1 --ip 10.0.1.0/24 --version 11 --timezone Asia/Shanghai --bbr --user root --password 123456
运行这个脚本后，会失联

**Comment by bohanyang** [comment]
你确定你的 IP 是 `10.0.1.0` ?
应该是 IP 不对，确认下内网 IP
