### ISSUE TITLE
安装后的内核似乎不包含 wireguard kernel module

### ISSUE THREAD

**Issue by Fangliding** [bohanyang/debi#102]
lsmod | grep wireguard 无输出
/sys/module/wireguard 找不到

但是apt update再upgard一下又好了 看日志好像它拉了一个新的kernel过来 挺纳闷的这玩意不应该是直接包含在kernel 5.6+中吗 我用version参数装的Debian11 先前已经确认过kernel版本是5.10 难道脚本默认装的是个不带wireguard的神秘内核吗

~~而且apt升级一下就好了 要不要考虑安装完成后自动运行 apt update && apt upgarde~~

**Comment by bohanyang** [comment]
lsmod | grep wireguard 无输出但是好像能用？

**Comment by bohanyang** [comment]
大概需要 `modprobe wireguard`
