### ISSUE TITLE
--cloud-kernel 参数要怎么写？无法指定

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bohanyang/debi#107]
root@Ran1950559481:~# ./debi.sh --cdn --network-console --cloud-kernel linux-image-cloud-amd64 --china --ethx --bbr --user root --password mjj233

Error: Unknown option: "linux-image-cloud-amd64".

root@Ran1950559481:~# ./debi.sh --cdn --network-console --cloud-kernel linux-image-6.1.0-13-cloud-amd64 --china --ethx --bbr --user root --password mjj233

Error: Unknown option: "linux-image-6.1.0-13-cloud-amd64".

**Comment by bohanyang** [comment]
--kernel  linux-image-cloud-amd64

--cloud-kernel  即可不需要具体指定
