### ISSUE TITLE
腾讯云轻量云广州区域 dd debian12 出现如下错误

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bohanyang/debi#108]
./debi.sh --cdn --network-console --cloud-kernel --china --ethx --bbr --user root --password xiaoxiao

用的这个命令 vnc报错

<img width="1044" alt="image" src="https://github.com/bohanyang/debi/assets/147643826/3abc8f2f-7018-492c-8efe-176256c05835">

**Comment by bohanyang** [comment]
/dev/vdb 是正确的盘吗？

**Comment by bohanyang** [comment]
按几次Alt+→，看下日志。没有日志不知道哪里有问题了。
