### ISSUE TITLE
请求新增设置swap功能

### ISSUE THREAD

**Issue by jhcn** [bohanyang/debi#109]

**Comment by long1215** [comment]
附议

**Comment by bohanyang** [comment]
我尝试整合下 cloud-init，这样可以通过 cloud config 配置

**Comment by bohanyang** [comment]
添加了 cloud init 支持，可以自定义 cloud config 脚本，仓库中有示例 https://github.com/bohanyang/debi/tree/master/cidata-example

`--cidata ./cidata-example` 即可
