### ISSUE TITLE
请教怎么可以正确dd到第二个硬盘

### ISSUE THREAD

**Issue by flhs0606** [bohanyang/debi#11]
甲骨文arm，已经给我dd坏了，我把这个坏的硬盘附加到另一台x86的机子上，新硬盘是sdb，尝试用脚本安装到sdb上，无效。用的--disk /dev/sdb参数；本项目有无镜像，可以手动dd到第二硬盘呢~~

**Comment by bohanyang** [comment]
1. 脚本不是 dd 镜像，是全新安装
2. 你在 x86 机器上安装的系统，当然不能在 arm 机器上启动

**Comment by bohanyang** [comment]
而且甲骨文的话，没什么灵活度的，最后还是要重新创建新机。
没有要留存的数据的话直接重开再运行脚本即可

**Comment by flhs0606** [comment]
> 而且甲骨文的话，没什么灵活度的，最后还是要重新创建新机。
> 没有要留存的数据的话直接重开再运行脚本即可

了解~
