### ISSUE TITLE
grub timeout 参数和bbr参数似乎无效？

### ISSUE THREAD

**Issue by lifetyper** [bohanyang/debi#110]
不知道是我理解有误差，这两个参数是只作用于安装过程吗？还是影响安装好的系统？
我设置了grub timeout 0，也开启了bbr选项。但是安装好以后我去看系统的/etc/default/grub 里面的timeout始终都是5，/etc/sysctl.conf里bbr也默认没有开启。

**Comment by bohanyang** [comment]
grub timeout 只适用于安装前系统。
BBR 配置在 /etc/sysctl.d/bbr.conf
https://github.com/bohanyang/debi/blob/88ee869a6ed3b7dc7c28dac3a69310eccc4fa9d2/debi.sh#L848
