### ISSUE TITLE
为啥设置了dns参数，dd完之后，没改变呢？

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bohanyang/debi#116]
curl -fLO https://raw.githubusercontent.com/bohanyang/debi/master/debi.sh && chmod a+rx debi.sh
./debi.sh --cdn --network-console --cloud-kernel --ethx --bbr --ssh-port 36 --user root --password passwd --dns '168.126.63.2 8.8.4.4 1.1.1.1'

上面命令dd完之后，查看 cat /etc/resolv.conf 显示的是

search 256.125.73.287.xxx.com
nameserver 8.8.8.8
nameserver 8.8.4.4

**Comment by bohanyang** [comment]
DNS 需要手动设置 IP 才能一起设定。IP是DHCP的话会用DHCP的DNS
