### ISSUE TITLE
Couldn't find any package by glob 'linux-modules-extra-5.10.0-23-arm64'

### ISSUE THREAD

**Issue by lsyyktv** [bohanyang/debi#119]
apt install linux-modules-extra-`uname -r`
![Q7J$E3NT`A$%`6A`K68WQ$8](https://github.com/bohanyang/debi/assets/39065858/6eef979b-f5f3-4d9f-86f2-14fb2cd794c9)
DD到debian11后，会有这个错误，请问要怎么解决？

**Comment by bohanyang** [comment]
Debian好像没有这个包吧

**Comment by lsyyktv** [comment]
> Debian好像没有这个包吧

请问能退回到ubuntu吗？因为这个似乎只能在ubutun下安装
