### ISSUE TITLE
大佬甲骨文 arm的vps求助

### ISSUE THREAD

**Issue by kissyouhunter** [bohanyang/debi#12]
新建的ARM的机器
配置：VM.Standard.A1.Flex
映像：Oracle-Linux-7.9-aarch64-2021.06.20-0

sudo ./debi.sh --cdn --network-console --bpo-kernel --ethx --bbr --user root --password XXXXXXX
安装完后没发现error（如下）
sudo shutdown -r now 重启
用installer用户登陆 使用的刚刚命令行里的设置的密码
显示认证失败
用原来的opc+公钥的验证这一正常登陆
大佬我是哪里操作错误了吗？
求教

d-i debian-installer/language string en
d-i debian-installer/country string US
d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us

# Network configuration

d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string arm
d-i netcfg/get_domain string
d-i hw-detect/load_firmware boolean true

# Network console

d-i anna/choose_modules string network-console
d-i preseed/early_command string anna-install network-console
d-i network-console/password password jbhunter1986
d-i network-console/password-again password jbhunter1986
d-i network-console/start select Continue

# Mirror settings

d-i mirror/country string manual
d-i mirror/protocol string https
d-i mirror/https/hostname string deb.debian.org
d-i mirror/https/directory string /debian
d-i mirror/https/proxy string
d-i mirror/suite string buster
d-i mirror/udeb/suite string buster

# Account setup

d-i passwd/root-login boolean true
d-i passwd/make-user boolean false
d-i passwd/root-password-crypted password $5$ixYiHNhV1uKkNsLf$q.nI4vatyIpRxLE4kkFjMGxDUL3wp39xxNMFfry/0V1

# Clock and time zone setup

d-i time/zone string UTC
d-i clock-setup/utc boolean true
d-i clock-setup/ntp boolean true
d-i clock-setup/ntp-server string 0.debian.pool.ntp.org

# Partitioning

d-i partman-auto/method string regular
d-i partman/early_command string debconf-set partman-auto/disk "$(list-devices disk | head -n 1)"
d-i partman-partitioning/default_label string gpt
d-i partman/default_filesystem string ext4
d-i partman-auto/expert_recipe string \
    naive :: \
        106 106 106 free \
            $iflabel{ gpt } \
            $reusemethod{ } \
            method{ efi } \
            format{ } \
        . \
        1075 1076 -1 $default_filesystem \
            method{ format } \
            format{ } \
            use_filesystem{ } \
            $default_filesystem{ } \
            mountpoint{ / } \
        .
d-i partman-auto/choose_recipe select naive
d-i partman-basicfilesystems/no_swap boolean false
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true

# Base system installation

d-i base-installer/kernel/image string linux-image-arm64

# Apt setup

d-i apt-setup/services-select multiselect updates, backports
d-i apt-setup/local0/repository string https://deb.debian.org/debian-security buster/updates main
d-i apt-setup/local0/source boolean true

# Package selection

tasksel tasksel/first multiselect ssh-server
d-i pkgsel/include string linux-image-arm64/buster-backports ca-certificates libpam-systemd
popularity-contest popularity-contest/participate boolean false

# Boot loader installation

d-i grub-installer/bootdev string default
d-i grub-installer/force-efi-extra-removable boolean true
d-i debian-installer/add-kernel-opts string net.ifnames=0 biosdevname=0

# Finishing up the installation

d-i finish-install/reboot_in_progress note
d-i preseed/late_command string in-target sh -c 'true; if [ ! -e "/etc/ssh/sshd_config.backup" ]; then cp "/etc/ssh/sshd_config" "/etc/ssh/sshd_config.backup"; fi; sed -Ei "s/^#?PermitRootLogin .+/PermitRootLogin yes/" /etc/ssh/sshd_config; { echo "net.core.default_qdisc=fq"; echo "net.ipv4.tcp_congestion_control=bbr"; } > /etc/sysctl.d/bbr.conf'
--2021-07-07 08:27:26--  https://deb.debian.org/debian/dists/buster/main/installer-arm64/current/images/netboot/debian-installer/arm64/linux
正在解析主机 deb.debian.org (deb.debian.org)... 151.101.90.132, 2a04:4e42:15::644
正在连接 deb.debian.org (deb.debian.org)|151.101.90.132|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：18761600 (18M)
正在保存至: “linux”

100%[===================================================================================>] 18,761,600  --.-K/s 用时 0.09s   

2021-07-07 08:27:31 (208 MB/s) - 已保存 “linux” [18761600/18761600])

--2021-07-07 08:27:31--  https://deb.debian.org/debian/dists/buster/main/installer-arm64/current/images/netboot/debian-installer/arm64/initrd.gz
正在解析主机 deb.debian.org (deb.debian.org)... 151.101.90.132, 2a04:4e42:15::644
正在连接 deb.debian.org (deb.debian.org)|151.101.90.132|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：27650501 (26M) [application/x-gzip]
正在保存至: “initrd.gz”

100%[===================================================================================>] 27,650,501  --.-K/s 用时 0.1s    

2021-07-07 08:27:32 (212 MB/s) - 已保存 “initrd.gz” [27650501/27650501])

8 块
GRUB_DEFAULT=debi
GRUB_TIMEOUT=5
GRUB_TIMEOUT_STYLE=menu
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.4.17-2102.202.5.el7uek.aarch64
Found initrd image: /boot/initramfs-5.4.17-2102.202.5.el7uek.aarch64.img
Found linux image: /boot/vmlinuz-0-rescue-170d8c12b21b46b4a130fcb2775bb5e2
Found initrd image: /boot/initramfs-0-rescue-170d8c12b21b46b4a130fcb2775bb5e2.img
done
menuentry 'Debian Installer' --id debi {
    insmod part_msdos
    insmod part_gpt
    insmod ext2
    linux /boot/debian-buster/linux net.ifnames=0 biosdevname=0
    initrd /boot/debian-buster/initrd.gz
}

**Comment by bohanyang** [comment]
> installer 用户登录
这个是用于新系统**安装过程中**查看安装日志，或者进行手动安装用的。安装完成之后就没有 installer 用户了

> 用原来的opc+公钥的验证这一正常登录
按照你的命令，成功安装后的新系统是用 root 登录的。但你原来的用户还能用，说明系统还是原来的，没有变。应该是因为脚本不支持 Oracle Linux，没能成功启动到 Debian 安装程序

脚本不支持 Oracle Linux。请重开机器并选择 Ubuntu 20.04 (不带 Minimal 镜像)
然后再次运行脚本

**Comment by kissyouhunter** [comment]
> > installer 用户登录
> 
> 这个是用于新系统**安装过程中**查看安装日志，或者进行手动安装用的。安装完成之后就没有 installer 用户了
> 
> > 用原来的opc+公钥的验证这一正常登录
> 
> 按照你的命令，成功安装后的新系统是用 root 登录的。但你原来的用户还能用，说明系统还是原来的，没有变。应该是因为脚本不支持 Oracle Linux，没能成功启动到 Debian 安装程序
> 
> 脚本不支持 Oracle Linux。请重开机器并选择 Ubuntu 20.04 (不带 Minimal 镜像)
> 然后再次运行脚本

哦哦
那我明白了
我是不习惯oracle linux
习惯用ubuntu
所以google搜到了你的脚本想试下
换成debian 看看
不支持度就算了
大佬辛苦

**Comment by bohanyang** [comment]
你懂我意思了吗，我说你模板选错了，不是选oracle linux，甲骨文默认模板就有ubuntu

**Comment by bohanyang** [comment]
只是他下拉菜单那里貌似没有ubuntu而已，你要选择没有minimal的那个模板，或者叫镜像

**Comment by kissyouhunter** [comment]
> 只是他下拉菜单那里貌似没有ubuntu而已，你要选择没有minimal的那个模板，或者叫镜像

arm架构的只让我选择oracle linux 
能改的只有操作系统版本（8 7.9 6.10）和镜像工作版本（2021.06.22-0  2021.05.12.-0）

**Comment by bohanyang** [comment]
免费arm架构的谁说只让选oracle linux
可以选ubuntu的

**Comment by kissyouhunter** [comment]
> 免费arm架构的谁说只让选oracle linux
> 可以选ubuntu的

成功了
是我傻了
以前都是看的minimal显示不支持
我就没选其他的
谢谢大佬
