### ISSUE TITLE
Use previous sources.list and resolv.sonf 

### ISSUE THREAD

**Issue by Suyun114** [bohanyang/debi#125]
Some IDCs like Tencent Cloud use an intranet mirror with intranet DNS resolved. There will be convenience to keep `sources.list` and `resolv.conf` in the new installed OS.

**Comment by bohanyang** [comment]
> sources.list

Another China-specific problem...
For servers in most of countries, the official global CDN mirror (deb.debian.org) is **very** fast ~enough~

>  There will be convenience to keep previous one

The goal that we use this script is to get rid of some shit included in the official OS template.
So I think it is better to provide the official one by default, while specify the one you want **explicitly** .

> resolv.conf

If you use DHCP it will follow DNS servers that provided by DHCP

**Comment by bohanyang** [comment]
So I mean, keeping the original config files doesn't work.
If resolv.conf use 127.0.0.1 but there's no DNS server in the new OS, the system will broken

**Comment by bohanyang** [comment]
If you want to use provider-provided (Tencent Cloud) DNS etc. it **should** be provided in DHCP (not by overriding the `resolv.conf`).
