### ISSUE TITLE
oracle arm dd debian11失败

### ISSUE THREAD

**Issue by qwinwin** [bohanyang/debi#14]
执行命令：
sudo ./debi.sh --cdn --network-console --ethx --bbr --user root --password passwd11 --bpo-kernel --suite bullseye

通过VNC连接上如图所示操作不了 不懂是不是bullseye的问题
https://dd-static.jd.com/ddimg/jfs/t1/188524/36/16016/73683/610568b2E0da644a4/ea2ff2613e602deb.png
![img](https://dd-static.jd.com/ddimg/jfs/t1/188524/36/16016/73683/610568b2E0da644a4/ea2ff2613e602deb.png)

**Comment by bohanyang** [comment]
ARM Debian 11 还没人试过呢，就你来踩坑啦 hh

**Comment by qwinwin** [comment]
> 都debian 11 bullseye了就已经是最新版kernel了
> 不要用backports了
> 去掉--bpo-kernel再试一下？



> ARM Debian 11 还没人试过呢，就你来踩坑啦 hh

哈哈哈哈 刚刷到一台就直接冲了 这台估计救不了了 vnc界面也无法键入 等新开到我再试试不用backports

**Comment by qwinwin** [comment]
> 都debian 11 bullseye了就已经是最新版kernel了
> 不要用backports了
> 去掉--bpo-kernel再试一下？

sudo ./debi.sh --cdn --network-console --ethx --bbr --user root --password passwd11 --suite bullseye

**Comment by kousyougi** [comment]
我验证这个指令可以用在Oracle arm的机子上
sudo ./debi.sh --version 11 --cloud-kernel --user root --password passwd123

安装完内核是
5.10.0-8-cloud-arm64

**Comment by bohanyang** [comment]
@kousyougi Debian 11 已经正式发布，使用最新版的脚本默认就是11。
