### ISSUE TITLE
脚本在使用ssh key作为登录凭据时仍要求设置密码

### ISSUE THREAD

**Issue by theConanEdogawa** [bohanyang/debi#15]
如题，可以加个有使用key来登录（`--authorized-keys-url`）的时候不需要设置密码（root用户下）

**Comment by bohanyang** [comment]
Debian 安装程序要求必需设置密码，
尽管之后可能不会用到（sudo也不需要密码的话）。

**Comment by bohanyang** [comment]
随意设置一个自己都记不住的密码，即可。

如果你担心的是安全问题（而不是流程问题），
**只要设置了 authorized-keys-url，脚本会关闭密码登录的**，反之则会开启。

**Comment by bohanyang** [comment]
https://github.com/bohanyang/debi/blob/b82cd0023ce22c704fdaed7c14901217b80ef98b/debi.sh#L447

**Comment by theConanEdogawa** [comment]
嗯，其实我两个问题都在意了，安全问题我刚刚没注意看脚本有这个逻辑，所以是没问题的；如果 Debian 要求一定要设置密码的话，那这样确实是最优解，多谢大佬解答。
