### ISSUE TITLE
低内存模式配置好像有问题

### ISSUE THREAD

**Issue by qwinwin** [bohanyang/debi#16]
`[ $((mem / 1024)) -lt 483 ] && kernel_params="$kernel_params lowmem/low="`
脚本中如上设置lowmem mode并没有自动进入低内存模式，vnc中依旧提示是否进入低内存模式
翻文档说`lowmem`值可以为1 2（没有找到1 2对应的含义），在最后加个 1 测试可以直接进入低内存模式，如下
```
menuentry 'Debian Installer' --id debi {
    insmod part_msdos
    insmod part_gpt
    insmod ext2
    linux /boot/debian-bullseye/linux net.ifnames=0 biosdevname=0 lowmem/low=1
    initrd /boot/debian-bullseye/initrd.gz
}
```

**Comment by bohanyang** [comment]
> vnc中依旧提示是否进入低内存模式

这是在什么机器上？我当时测试的时候用的 AWS 最低配（<512M 内存）确认可以进入低内存模式。
脚本有把 ` lowmem/low=` 加到 grub menu entry 的启动参数吧（也就是说探测了到内存小于 483）？

这些配置好多都没文档。lowmem/low 只是代表那个提示，给他随便设个值（比如空值）应该可以跳过这个提示。
源码在这里: https://salsa.debian.org/installer-team/lowmem/-/blob/master/debian/lowmemcheck.templates

能否帮忙测试下手工修改为 `lowmem/low=""` 能否跳过提示？

**Comment by qwinwin** [comment]
> > vnc中依旧提示是否进入低内存模式
> 
> 这是在什么机器上？我当时测试的时候用的 AWS 最低配（<512M 内存）确认可以进入低内存模式。
> 脚本有把 ` lowmem/low=` 加到 grub menu entry 的启动参数吧（也就是说探测了到内存小于 483）？
> 
> 这些配置好多都没文档。lowmem/low 只是代表那个提示，给他随便设个值（比如空值）应该可以跳过这个提示。
> 源码在这里: https://salsa.debian.org/installer-team/lowmem/-/blob/master/debian/lowmemcheck.templates
> 
> 能否帮忙测试下执行脚本后手工修改 /boot/grub/grub.cfg， `lowmem/low=""` 能否跳过提示？

机器为justhost的kvm 512内存
刚刚在debian11上（MemTotal为 484488）试了下 原脚本可以直接进入低内存模式
然后重装justhost的官方镜像 发现内存涨了 变成 494796  除以1024刚好483 所以脚本的`-lt 483`条件不满足了 尴尬- -
改成`-le 483`或者把阈值设高点应该就行了

**Comment by bohanyang** [comment]
已调高至 ≥512

**Comment by SekiBetu** [comment]
这个阈值的判断有必要吗，直接跳过不就好了？刚才在一个700多M的机子上装，没反应，上VNC一看卡在低内存模式的确认上了，我改成 -le 1024了才能顺利安装

**Comment by bohanyang** [comment]
嗯，你这么一说好像确实没必要。
内存够大的情况下，就算加了 lowmem/low 也不会进入低内存模式的话，就没必要了

**Comment by bohanyang** [comment]
话说内存 700 应该够大了啊。是x86_64的机器吧。

**Comment by SekiBetu** [comment]
我也不知道为什么，之前我在这家机子上装没问题的，这次装进入低内存模式了，保险起见还是别设阈值了吧

**Comment by bohanyang** [comment]
去掉判断了
