### ISSUE TITLE
Doesn't quite work on Oracle cloud x86 ver.

### ISSUE THREAD

**Issue by B83C** [bohanyang/debi#17]
What I have tried is running the commands on a ubuntu 20.04 free tier vm. However, it did not boot whatsoever. But it works perfectly fine on the arm variants.
Any ideas? Or is there something I've missed?

**Comment by bohanyang** [comment]
I can't know what's wrong without details

**Comment by B83C** [comment]
These are the devices on the vm
```
ubuntu@v2:~$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0    0 70.4M  1 loop /snap/oracle-cloud-agent/20
loop1     7:1    0 55.5M  1 loop /snap/core18/2074
loop2     7:2    0 32.3M  1 loop /snap/snapd/12398
sda       8:0    0 46.6G  0 disk
├─sda1    8:1    0 46.5G  0 part /
├─sda14   8:14   0    4M  0 part
└─sda15   8:15   0  106M  0 part /boot/efi
```

while this is the command I fired at the machine:
```
ubuntu@v2:~$ sudo ./debi.sh --cdn --network-console --architecture amd6
 --ethx --bbr --user root --password lellel123 --disk /dev/sda1
```
The output was without any hints of what is wrong.

And I just rebooted the machine, and selected the debian installer option in grub (from the serial console), unfortunately, it kinda froze without any sign of life.

**Comment by bohanyang** [comment]
(Are you sure? `--architecture amd6` rather than amd6**4**)

Here's the problem and my suggestions:

1. You **usually don't** have to specify architecture manually, it'll be **auto-detected**
2. `--disk` accepts **disk** device like `/dev/sda` rather than a **partition** like `/dev/sda1`. I do have an exmaple in the README. Also you **don't** have to specify it **if there's only one** disk.
3. The serial console and the VNC of Oracle Cloud is kind of broken now. You should not enter/input any thing to it. The `Debian Installer` option in GRUB should be selected and booted **automatically**.

So please try again.

**Comment by B83C** [comment]
First of all, I am certain that I wrote amd64 correctly and that it the last character was cut due to my resizing the terminal (a quirk of the st terminal)
and second of all, the line I sent was one of the few attempts I had and of course I ran the default line ( the one you wrote in zhong wen ), but the machine just wouldn't yield anything.
lastly, the serial console has never been broken to me at least. The Debian Installer I see is also selected as default, so this shouldn't be problematic.

**Comment by bohanyang** [comment]
> the machine just wouldn't yield anything
How long of time had you wait? Have you tried ping the server? Have you tried ssh the server?

**Comment by B83C** [comment]
To give you a picture of what happened
https://user-images.githubusercontent.com/72597973/128633765-6430c32d-6966-421b-871f-4cb6fa3b9b47.mp4

**Comment by bohanyang** [comment]
So, what I mean is that the serial console **is** broken here.
Maybe it's a bug of Oracle or Debian Installer.
Yes, the serial console has never been broken to you.
But it's only for a running OS with proper config, not for the Debian Installer.

Have you tried to ping/ssh the server after that?
If you enabled `--network-console`

**Comment by bohanyang** [comment]
Serial console is black ≠ Machine is dead

**Comment by B83C** [comment]
Oh god I am so stupid! I tried establishing an ssh connection and it magickly worked ~ 
Sorry for wasting your time on this trivial stuff that could have avoid all this hassle if I have waited longer...
Once again, thank you for your help!

**Comment by B83C** [comment]
![image](https://user-images.githubusercontent.com/72597973/128634407-0bfab9ec-4481-40df-aa52-dd190e585619.png)

**Comment by B83C** [comment]
Issue fixed It was my wrong assumption
