### ISSUE TITLE
可否增加支持重装为kali？

### ISSUE THREAD

**Issue by 10467106** [bohanyang/debi#18]
Oracle ARM 小鸡，使用大佬的脚本重装 debian 是没问题的，但是手动安装 Kali 后，机器启动完无法SSH连接，且 VNC 无法操作只能查看，使用VNC附带的 ctrl+alt+delete 也不生效。请问大佬可否直接支持 kali 安装呢？

**Comment by 10467106** [comment]
已查找到问题原因 debian默认网卡名是 ens0pX，kali 默认网卡名是 eth0 所以导致出现网络不通。

**Comment by bohanyang** [comment]
> 使用大佬的脚本重装 debian 是没问题的，但是手动安装 Kali 后
不是很明白你的“脚本重装 debian 后又手动安装 Kali”是什么意思

> debian 默认网卡名是 ens0pX
脚本支持选项 `--ethx`，回退旧格式的网卡名

**Comment by bohanyang** [comment]
或者安装后修改 `/etc/default/grub` 在 `GRUB_CMDLINE_LINUX` 值后追加 ` net.ifnames=0 biosdevname=0`
然后 `sudo update-grub`  并重启

**Comment by 10467106** [comment]
> > 使用大佬的脚本重装 debian 是没问题的，但是手动安装 Kali 后
> 
> 不是很明白你的“脚本重装 debian 后又手动安装 Kali”是什么意思
> 
> > debian 默认网卡名是 ens0pX
> 
> 安装脚本支持选项 `--ethx`，使用旧格式的网卡名。

脚本重装 debian 后又手动安装 Kali 是用脚本把 Ubuntu 20 ARM 机重装为 Debian，然后手动配置源为 Kali 源，然后安装 Kali。
Kali 基于 Debian Testing，也支持网络安装，请问可否让脚本支持直接安装 Kali。

**Comment by bohanyang** [comment]
我暂时没有这个需求，你有兴趣可以试着研究下。
镜像源什么的都可以换的。
