### ISSUE TITLE
Debian 11 Security源更名

### ISSUE THREAD

**Issue by theConanEdogawa** [bohanyang/debi#19]
根据 https://www.debian.org/releases/testing/amd64/release-notes/ch-information.en.html#security-archive
当 `$suite` 为 `bullseye` 的时候，应该是 `d-i apt-setup/local0/repository string $security_repository $suite-security main`

**Comment by bohanyang** [comment]
非常感谢！这几天没空，我要过几天再更新，你急的话可以开个 PR

**Comment by theConanEdogawa** [comment]
#20 已提交PR

**Comment by bohanyang** [comment]
已修复，再次感谢！
