### ISSUE TITLE
invalid magic number, you need to load kernel first

### ISSUE THREAD

**Issue by qy2009** [bohanyang/debi#22]
我做完后重启，启动时候选了debian installer.

然后就提示了：

error: invalid magic number
error: you need to load the kernel first

我试了一下system setup. 就自动重起。

但是可以进入之前的系统 。

谢谢啦

**Comment by bohanyang** [comment]
什么机器什么命令

**Comment by qy2009** [comment]
Oracle ARM. 

用的是 sudo ./debi.sh --architecture arm64 --user root --password password

本来是oracle linux, 我用moeclub 的刷成了debian 10. (刷成功了，但是显示是x64).

**Comment by bohanyang** [comment]
> 刷成功了，但是显示是x64

ARM 不可能装 x64 的系统。那就应该不是我脚本的问题了吧。
