### ISSUE TITLE
Debian 11 不支持重装为 Debian 10

### ISSUE THREAD

**Issue by tonyzhou777** [bohanyang/debi#26]
1. 用脚本重装成 Debian 11
2. 再次用脚本重装成 Debian 10 时报错：
![BaiduShurufa_2021-9-13_11-49-55](https://user-images.githubusercontent.com/41107018/133021264-c5bfa102-4a67-485b-880c-60d2488b71f1.png)

**Comment by bohanyang** [comment]
刚在 Lightsail 上测试过 Debian 11 是可以正常带起 Debian 10 的 installer 的。

看错误信息的话是 `/boot` 分区不对，跟 Debian 版本无关。
请问这是什么机器？

**Comment by tonyzhou777** [comment]
> 刚在 Lightsail 上测试过 Debian 11 是可以正常带起 Debian 10 的 installer 的。
> 
> 看错误信息的话是 `/boot` 分区不对，跟 Debian 版本无关。
> 请问这是什么机器？

哦哦，原来是这样。

是甲骨文的AMD机型，谢谢大佬回复。

**Comment by bohanyang** [comment]
能装 Debian 11 就肯定能装 10 的，应该是没问题的。
执行完脚本后，系统里看确实有 /boot/debian-buster/linux 这个文件的吧。
另外执行 `cat /boot/grub/grub.cfg | grep /boot` 命令看看有没有类似如下的输出：
```
        linux   /boot/vmlinuz-5.10.0-8-amd64 root=UUID=2588b294-dda1-4b4e-9148-6176754e5160 ro  quiet
        initrd  /boot/initrd.img-5.10.0-8-amd64
                linux   /boot/vmlinuz-5.10.0-8-amd64 root=UUID=2588b294-dda1-4b4e-9148-6176754e5160 ro  quiet
                initrd  /boot/initrd.img-5.10.0-8-amd64
                linux   /boot/vmlinuz-5.10.0-8-amd64 root=UUID=2588b294-dda1-4b4e-9148-6176754e5160 ro single
                initrd  /boot/initrd.img-5.10.0-8-amd64
```

**Comment by tonyzhou777** [comment]
> 能装 Debian 11 就肯定能装 10 的，应该是没问题的。
> 执行完脚本后，系统里看确实有 /boot/debian-buster/linux 这个文件的吧。
> 另外执行 `cat /boot/grub/grub.cfg | grep /boot` 命令看看有没有类似如下的输出：
> 
> ```
>         linux   /boot/vmlinuz-5.10.0-8-amd64 root=UUID=2588b294-dda1-4b4e-9148-6176754e5160 ro  quiet
>         initrd  /boot/initrd.img-5.10.0-8-amd64
>                 linux   /boot/vmlinuz-5.10.0-8-amd64 root=UUID=2588b294-dda1-4b4e-9148-6176754e5160 ro  quiet
>                 initrd  /boot/initrd.img-5.10.0-8-amd64
>                 linux   /boot/vmlinuz-5.10.0-8-amd64 root=UUID=2588b294-dda1-4b4e-9148-6176754e5160 ro single
>                 initrd  /boot/initrd.img-5.10.0-8-amd64
> ```

我在 Win10 VMware Workstation 16 下虚拟的 Debian 10 上又试了下：

1. 从 Debian 10 重装成 Debian 11，成功。
`bash debi.sh --china --user root --password test`
2. 从 Debian 11 重装成 Debian 10，成功。
`bash debi.sh --china --user root --password test --version 10`
3. 从 Debian 10 重装成 Debian 11，成功。
`bash debi.sh --china --network-console --ethx --bbr --user root --password test --filesystem btrfs`
4. 从 Debian 11 重装成 Debian 10，失败。`reboot` 前执行 `cat /boot/grub/grub.cfg | grep /boot` 并截图。
`bash debi.sh --china --network-console --ethx --bbr --user root --password test --filesystem btrfs --version 10`
![BaiduShurufa_2021-9-15_23-5-3](https://user-images.githubusercontent.com/41107018/133459804-19b752c3-9a95-4397-bc30-e00e0630fb58.png)
![BaiduShurufa_2021-9-15_23-5-22](https://user-images.githubusercontent.com/41107018/133459832-553728d9-cc6b-4013-acdf-160bb4d10ad4.png)

初步怀疑是不是 `--filesystem btrfs` 这个传参的问题？谢谢。

**Comment by bohanyang** [comment]
很明显就是 --filesystem btrfs 的问题嘛

GRUB 需要读取 /boot 里的文件嘛
可是文件系统是 btrfs，不支持读取。
我 grub entry 只有 insmod ext2 嘛，只支持从 ext3 ext4 系列文件系统读取

**Comment by bohanyang** [comment]
情况太特殊了……

**Comment by bohanyang** [comment]
受此 issue 启发，已经更新支持 xfs。

btrfs 因为有 subvolume 结构，不能通用 `/boot` 前缀，比如你这个是 `/@rootfs/boot`
所以暂时不考虑添加 btrfs 下的支持。但也不是完全不能用，
你可以手工修改 `/boot/grub/grub.cfg` 最后面的 "Debian Installer" entry
把  `/boot` 改为 `/@rootfs/boot` 即可。测试过可以正常启动安装程序。

**Comment by tonyzhou777** [comment]
> 受此 issue 启发，已经更新支持 xfs。
> 
> btrfs 因为有 subvolume 结构，不能通用 `/boot` 前缀，比如你这个是 `/@rootfs/boot` 所以暂时不考虑添加 btrfs 下的支持。但也不是完全不能用， 你可以手工修改 `/boot/grub/grub.cfg` 最后面的 "Debian Installer" entry 把 `/boot` 改为 `/@rootfs/boot` 即可。测试过可以正常启动安装程序。

谢谢大佬

**Comment by bohanyang** [comment]
@tonyzhou777 感谢 @Chm #49 
已经支持 btrfs 还请测试下

**Comment by tonyzhou777** [comment]
> @tonyzhou777 感谢 @Chm #49 已经支持 btrfs 还请测试下

收到，感谢
