### ISSUE TITLE
求支持独服网络安装

### ISSUE THREAD

**Issue by hietsusama** [bohanyang/debi#27]
谢谢大佬 脚本很好用 VPS都能dd
最近搞了一个垃圾独服不带IPMI 想dd d10 自带的镜像分区有问题

![image](https://user-images.githubusercontent.com/38307139/133921598-a5b77dcc-5227-4094-a706-cd927f06f3b9.png)

两块硬盘，一个SSD 一个HDD 我想装到SSD上，HDD开机后我自己挂载。

是否可以支持，谢谢大佬

**Comment by bohanyang** [comment]
可以添加 `--no-disk-partitioning` 然后手动进行硬盘分区
