### ISSUE TITLE
不能重装Debian9吗？

### ISSUE THREAD

**Issue by justhy** [bohanyang/debi#28]
我看脚本里有判断可以装Debian9，但是安装失败。
![Snipaste_2021-09-21_15-15-14](https://user-images.githubusercontent.com/17880968/134127945-1f41b85a-7857-4e4f-a8c8-0a40cd01b287.png)

**Comment by bohanyang** [comment]
我这边试是OK的，你加了什么特殊的参数吗

**Comment by justhy** [comment]
bash <(wget --no-check-certificate -qO- 'https://raw.githubusercontent.com/bohanyang/debi/master/debi.sh') --version 9 --cdn --network-console --ethx --bbr --user root --password 密码 --timezone Asia/Shanghai

**Comment by justhy** [comment]
甲骨文的AMD64，ubuntu20和18都不行

**Comment by bohanyang** [comment]
拜托不要用这种方式传脚本。

因为脚本 wget 下载完之前 bash 就会执行。而且我的脚本为了实现密码输入会读取 stdin 等，所以可能会出问题。
你想要一条命令的话，可以用 && 连起来或者用 sh 或 bash 的 -c 选项，脚本选项前加 `--`

`sh -c "$(wget -qO- https://raw.githubusercontent.com/bohanyang/debi/master/debi.sh)" -- --version 9`

**Comment by justhy** [comment]
使用分开的命令进行安装，出现同样的错误。。。

**Comment by bohanyang** [comment]
ssh 到 installer 之后第一屏（不切换到日志界面）可以操作吗，会报错吗

**Comment by justhy** [comment]
可以操作的
![Uploading Snipaste_2021-09-21_16-04-42.png…]()

**Comment by justhy** [comment]
fdisk -l
![Snipaste_2021-09-21_16-09-43](https://user-images.githubusercontent.com/17880968/134135557-aafd12c4-5fd1-4123-b221-cf034fd57af7.png)

cat preseed.cfg 太长，无法往上滚动
![Snipaste_2021-09-21_16-10-17](https://user-images.githubusercontent.com/17880968/134135640-9f7de437-1d3f-4fe2-8c48-fc1b93b1b80a.png)

**Comment by bohanyang** [comment]
这个界面输入命令 `list-devices disk | head -n 1`

输出应该是 /dev/sda 才对，你试试呢

**Comment by justhy** [comment]
有的
![Snipaste_2021-09-21_16-14-30](https://user-images.githubusercontent.com/17880968/134136122-81c856dc-a905-4e43-bd6f-8989b14c6865.png)

**Comment by bohanyang** [comment]
应该是没问题的呀。日志那一屏还是没有任何变化吗

**Comment by justhy** [comment]
还是老样子，没有变化
![Snipaste_2021-09-21_16-16-53](https://user-images.githubusercontent.com/17880968/134136500-901b8e9f-4a71-42bc-85f1-03fbe4d56bfd.png)

**Comment by bohanyang** [comment]
之前试过装Debian 10 和 11 都没问题的吗？

**Comment by justhy** [comment]
有装过10没有问题的

**Comment by bohanyang** [comment]
有 telegram 吗
我帮你看看`@brentybh`

**Comment by bohanyang** [comment]
可能是 Debian 9 安装程序的 bug 吧。应该只影响 UEFI 启动的机器。
