### ISSUE TITLE
腾讯云国内遇到的问题

### ISSUE THREAD

**Issue by ylx2016** [bohanyang/debi#30]
分别提示
./debi.sh: 100: ./debi.sh: http_proxy: parameter not set
./debi.sh: 105: ./debi.sh: https_proxy: parameter not set
我是把debi.sh下载后传上去的，运行后不同参数提示上面不同的错误
不知道是不是设计大陆就必须要设置http_proxy/http2_proxy代理？

**Comment by bohanyang** [comment]
已经修复，请重试

**Comment by bohanyang** [comment]
刚刚给脚本增加了指定代理的功能，但是代码有些问题，抱歉了。
此问题已经修复。
