### ISSUE TITLE
无法连到installer用户看进度

### ISSUE THREAD

**Issue by SekiBetu** [bohanyang/debi#31]
```shell
sudo ./debi.sh --network-console --version 11 --user root --password <新系统用户密码> --authorized-keys-url https://github.com/SekiBetu.keys --timezone Asia/Shanghai
```
是不是加了这个--authorized-keys-url就不能连入了

还有一个问题就是我原本服务器把默认的22端口换掉了，会不会也会导致这个问题

**Comment by SekiBetu** [comment]
约 30 秒后可以尝试 SSH 登录 installer 用户，密码与之前设置的相同。如果成功连接，可以按 Ctrl-A 然后再按 4 监控安装日志。安装完成后会自动重启进入新系统。
这句话到底啥意思，用户名是 installer 然后密码是 <新系统用户密码> 嘛，连不进去啊，我在后台VNC能看到进度，但是连是连不进的

**Comment by SekiBetu** [comment]
看了眼英语的安装过程，确实没有监控安装过程的描述，估计是没这个功能吧

**Comment by bohanyang** [comment]
> 用户名是 installer 然后密码是 test123
对的

> 安装过程SSH连不进去
可能是机器没有成功联网。你看能不能ping通

**Comment by SekiBetu** [comment]
> > 用户名是 installer 然后密码是 test123
> 
> 对的
> 
> > 安装过程SSH连不进去
> 
> 可能是机器没有成功联网。你看能不能ping通

![image](https://user-images.githubusercontent.com/38283893/135741237-1b2434ba-8d35-496e-93e5-4ccc3c0758d0.png)

**Comment by SekiBetu** [comment]
我换别的脚本了，死活装不上

**Comment by bohanyang** [comment]
就是DHCP自动配置网络失败了，我试试

**Comment by bohanyang** [comment]
digitalocean 没有 dhcp 了，要手动配置网络。(挺差劲的)
例如 `--ip 45.55.49.104/19 --gateway 45.55.32.1 --dns "67.207.67.2 67.207.67.3"`

Ubuntu 20 的网络配置文件：`cat /etc/netplan/50-cloud-init.yaml`
Ubuntu 18或Debian：`/etc/network/interfaces`

**Comment by SekiBetu** [comment]
https://www.cxthhhhh.com/Network-Reinstall-System-Modify 这个脚本没让手动配置也装上了，啥原理

**Comment by SekiBetu** [comment]
> digitalocean 没有 dhcp 了，要手动配置网络。(挺差劲的) 例如 `--ip 45.55.49.104/19 --gateway 45.55.32.1 --dns "67.207.67.2 67.207.67.3"`
> 
> Ubuntu 20 的网络配置文件：`cat /etc/netplan/50-cloud-init.yaml` Ubuntu 18或Debian：`/etc/network/interfaces`

`--dns` 配置项如果不用的话默认是 `localhost` 吗，`--netmask` 需要配置吗

**Comment by bohanyang** [comment]
>--dns 配置项如果不用的话默认是 localhost 吗

https://github.com/bohanyang/debi#available-options
文档中配置项后面的就是默认值，如这里是`'8.8.8.8 8.8.4.4'`谷歌DNS

>--netmask 需要配置吗

如果你 --ip 选项已经配置了 cidr 如 `45.55.49.104/19` 中的 `/19` 则不用配置。
否则要配置，cidr 与 netmask 对应表可以参考 https://ip.sb/cidr/

**Comment by SekiBetu** [comment]
还有一个问题啊，如果我用的 `--user` 不是root的话，假如是 `--user sekibetu` 那么这个用户会被赋予root权限吗，还是说是普通用户，如果sekibetu是普通用户，那么root用户的密码没设？

**Comment by SekiBetu** [comment]
`--authorized-keys-url` 这个选项是否影响 `installer` 登录，我登录了几次都提示错误

**Comment by bohanyang** [comment]
你加了key就必需要用key登录installer。不能用密码了。

**Comment by bohanyang** [comment]
sekibetu 是普通用户，但是有免密码sudo权限。
root用户的密码确实没设，但是是禁止登录的，也就是说不论什么密码都是密码错误。

**Comment by SekiBetu** [comment]
> 你加了key就必需要用key登录installer。不能用密码了。

那我 `--password` 选项可以不加？

**Comment by bohanyang** [comment]
还是要加。详见这个issue

https://github.com/bohanyang/debi/issues/15#issuecomment-890505489

**Comment by SekiBetu** [comment]
没事了，懂了，摸透了
