### ISSUE TITLE
大佬 --network-console 的密码怎么不对啊

### ISSUE THREAD

**Issue by pengkaiwei** [bohanyang/debi#33]
sudo ./debi.sh --architecture arm64 --network-console --bbr --user root --password password66

安装查看 Installer用户，密码password66

总是提示错误

**Comment by bohanyang** [comment]
是甲骨文吗？

**Comment by SekiBetu** [comment]
https://github.com/bohanyang/debi/issues/31#issuecomment-932867595 说不定是甲骨文没有DHCP？我没甲骨文账号，试不了，楼主自己指定IP 网关等参数试试

**Comment by bohanyang** [comment]
先关闭吧，有进展可以再补充
