### ISSUE TITLE
能否增加选择网卡选项?

### ISSUE THREAD

**Issue by JustTestCode** [bohanyang/debi#37]
能否增加选择网卡选项?
有的时候服务器有两张网卡,默认第一个eth0没有插线,eth1才有线. 安装过程中默认配置的是eth0,造成无网没法安装

**Comment by bohanyang** [comment]
这个可以加

**Comment by bohanyang** [comment]
已经加了，可以麻烦测试下最新版有没有问题吗

**Comment by JustTestCode** [comment]
有个问题容易歧义,我是试了几次才行
指定的网卡如果用DD之前系统内的网卡的名字:enp3s* 还是无效,
必须要指定类似eth*这样的才能正常连接网络装系统,不然还是提示网络配置错误

**Comment by bohanyang** [comment]
你加了 --ethx 选项的话就是 eth*
否则应该默认是新式命名的 enp3s*
