### ISSUE TITLE
DD后甲骨文无故跑流量，CPU飙升

### ISSUE THREAD

**Issue by AndersonGhost** [bohanyang/debi#39]
如题所述，DD甲骨文后，系统无缘无故进行大量网络上传动作，流量巨大，CPU也随之飙升。已经有6台机器DD后，是这种现象了，如下图所示：DD后没有安装任何挖矿脚本，只是安装了个探针，不然也不知道DD后居然跑这么多的流量。另外，使用了其他家的DD脚本，目前还从未出现如此跑流量的现象（在出现了跑流量的现象后，使用其他家的DD脚本重装系统，问题解决）。
![image](https://user-images.githubusercontent.com/33820659/141702582-d4cdd327-d702-483d-988c-68fed959ec5b.png)
![image](https://user-images.githubusercontent.com/33820659/141702627-a01c343b-58e8-4e1b-9cdb-ae80b71c04f6.png)

**Comment by bohanyang** [comment]
this is impossible

> 只是安装了个探针

那就是探针的问题了。。。

**Comment by AndersonGhost** [comment]
使用了其他DD脚本也装了探针，没有出现这个问题啊

跑流量这个现象出了6台机器了o(╯□╰)o

安装方式为：使用甲骨文自带ubuntu 20.04系统启动， 然后使用：
curl -fLO https://raw.githubusercontent.com/bohanyang/debi/master/debi.sh && chmod a+rx debi.sh
sudo ./debi.sh --cdn --network-console --ethx --bbr --user root --password 密码

进行安装，过了一段时间后，就出现跑流量的现象了。

我是观察了一段时候后，才来发帖子的。

**Comment by bohanyang** [comment]
所以你能大概猜一下可能是哪里的问题吗

我脚本没有装任何东西哦

**Comment by bohanyang** [comment]
这么久了，好像也没有其他人反馈这个问题呢

**Comment by AndersonGhost** [comment]
好的，那先关闭吧   我自己先找找原因

**Comment by ceozero** [comment]
> 这么久了，好像也没有其他人反馈这个问题呢

我一直有这个问题。开始以为是 nezha 的问题。在那边肝了很久没找到原因。后面发现是因为 go 语言的一个获取系统流量的库导致的。。但是如果不是用这个脚本 D 的系统， 就没啥问题。

有很多探针都是用 go 写的话，都会调用到gopsutil那个库来获取流量信息。

https://github.com/nezhahq/agent/issues/139#issuecomment-2543831423

不知道大佬能不能破案。。

澄清一下，它不是偷跑流量，是把系统开机以来的所有流量会偶尔的计算到周期性流量统计。而且不是每次都出现。会间隔几个小时就会来一次。

最后也没找到解决方案。一两年了。也没管，最近升级 nezha 的 v1 版本还是发现这个问题。就搜了一圈。。。终于搜到同款了。不容易。。。。。
