### ISSUE TITLE
加载网卡驱动

### ISSUE THREAD

**Issue by hietsusama** [bohanyang/debi#40]
大佬，想问一下有台独服BCM网卡，必须加载bnx2x-e2-7.13.1.0.fw 网卡驱动，但是远程IPMI只能加载一个ISO，全量上传又出错。
https://github.com/wkennington/linux-firmware/blob/master/bnx2x/bnx2x-e2-7.13.1.0.fw
https://packages.debian.org/bullseye/firmware-bnx2x

这种情况有什么思路吗
感谢大佬

**Comment by bohanyang** [comment]
???跟脚本有什么关系吗
