### ISSUE TITLE
报告一个 bug

### ISSUE THREAD

**Issue by Acytoo** [bohanyang/debi#42]
BuyVM 512 MB 的机器，初始 OS Debian 11，BIOS, 想 dd 重装 Debian 11。

---------------------------------

执行了命令，重启不安装，发现一个 python 的 wait signal 的进程，感觉应该是这个。

VNC 连接上看，发现 Grub 第一个目录不是installer，是正常启动。

grub 页面手动选择安装，则开始正常安装。

机器本来没有 grub ，自己新安装的grub，应该不是这个问题吧。

以前在甲骨文 ARM 上直接重启就安装了，这个机器需要手动选择，是个 bug ？

**Comment by bohanyang** [comment]
> 发现一个 python 的 wait signal 的进程，感觉应该是这个

脚本并没有（在启动阶段）用到 python

> 是个 bug

我的 GRUB 启动配置是写在 /etc/default/grub.d/zz-debi.cfg 的。大部分系统都有读取这个目录。至于 buyvm 上为什么没读取那就要研究下了。

另外，适配所有主机商，应对所有情况是不可能的。

**Comment by Acytoo** [comment]
> > 发现一个 python 的 wait signal 的进程，感觉应该是这个
> 
> 脚本并没有（在启动阶段）用到 python
> 
> > 是个 bug
> 
> 我的 GRUB 启动配置是写在 /etc/default/grub.d/zz-debi.cfg 的。里面有把默认 entry 设为 debian installer。至于 buyvm 上为什么没生效那就要研究下了。
> 
> 另外，适配所有主机商，应对所有情况是不可能的。

ok, 懂了
