### ISSUE TITLE
大佬 甲骨文 用纯v6 脚本安装后，后期有v4 了 ，怎么添加，谢谢！

### ISSUE THREAD

**Issue by pengkaiwei** [bohanyang/debi#43]
大佬 甲骨文 用纯v6 脚本安装后，后期有v4 了 ，怎么添加，谢谢！
https://github.com/bohanyang/debi/wiki/%E7%94%B2%E9%AA%A8%E6%96%87%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%BA%AF-IPv6-%E7%BD%91%E7%BB%9C%EF%BC%88%E6%97%A0%E5%85%AC%E7%BD%91-IPv4%EF%BC%89%E4%B8%8B%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95

**Comment by pengkaiwei** [comment]
dd脚本
sudo ./debi.sh --cdn --network-console --ethx --bbr --user root --password xxxxx --ip 2603:xxxx::xxxx/64 --gateway none

然后修改文件
/etc/network/interfaces

添加
iface eth0 inet dhcp

重启就好了。


不知能否纯ipv6 dd的时候，也保留ipv4

**Comment by bohanyang** [comment]
暂时不支持。Debian 安装程序只能配一个 IP 地址。
