### ISSUE TITLE
DD debian11 过程中卡在download installer components

### ISSUE THREAD

**Issue by Terry-Lzz** [bohanyang/debi#45]
![image](https://user-images.githubusercontent.com/60741927/147528199-422ac2a1-84cb-4cd2-b85c-d926e284c0fb.png)

DD机器为ruvds家的1H 512M 机器 ，10G硬盘， hyper-v虚拟化
DD前原系统已测试过ubuntu 18.04 ， debian 9 和 10

所使用的命令如下：

sudo ./debi.sh --network-console --ethx --bbr --cdn \
	--version 11 \
	--user root \
	--password XXXXXXXXXX \
	--ssh-port XXXX \
	--timezone Asia/Shanghai \
	--install 'apt-transport-https ca-certificates sudo vim wget curl net-tools git unzip man-db xz-utils python3 python3-pip jq nload' \
	--ip XXX \
	--gateway XXX \
	--netmask XXX

机器没有DHCP，命令中指定的网络参数是和原系统一样的。

如果全部选上的话，会卡在如下界面：
![image](https://user-images.githubusercontent.com/60741927/147529186-fd5adcf5-fc99-4792-8f09-604ffe5ffa5e.png)

如果不选，直接回车的话，会继续卡在如下界面：
![image](https://user-images.githubusercontent.com/60741927/147528519-8212f6ef-48d4-4ff9-adbb-e2de6e821b81.png)

这是检测不到硬盘？ 
附上dd 9版本后的分区情况：
![image](https://user-images.githubusercontent.com/60741927/147528776-612c8cd1-2862-44fd-a5d4-da3a2cf51f50.png)

但是同样命令，dd选择 9 和 10版本均可以正常自动安装，就dd 11版本就会出现这个问题，请问哪里出了问题？

**Comment by bohanyang** [comment]
看上去第一张图，是因为内存低（进入了低内存模式）才出现的

>dd选择 9 和 10版本均可以正常自动安装，就dd 11版本就会出现这个问题

这个确实有点奇怪

**Comment by Terry-Lzz** [comment]
> 看上去第一张图，是因为内存低（进入了低内存模式）才出现的
> 
> > dd选择 9 和 10版本均可以正常自动安装，就dd 11版本就会出现这个问题
> 
> 这个确实有点奇怪


选择 9 和 10 版本安装 , 也会自动进入低内存模式，但是能够完成自动安装流程，正常开机。但是11就会如上所述无法正常安装。

**Comment by joyoner** [comment]
遇到了同样的问题。

**Comment by bohanyang** [comment]
> 遇到了同样的问题。

机器信息可以提供下吗？
主机商（不介意的话），虚拟化平台，配置，原系统等

**Comment by joyoner** [comment]
> 

你的联系方式，我把机器的登录信息发你。

**Comment by bohanyang** [comment]
telegram 和我 twitter 用户名相同，见我主页

**Comment by bohanyang** [comment]
@Terry-Lzz 可以用更新版试一下吗


```
curl -fLO https://raw.githubusercontent.com/bohanyang/debi/force-lowmem/debi.sh && chmod a+rx debi.sh
```
添加这个参数
```
--force-lowmem 1
```

**Comment by syouko** [comment]
> @Terry-Lzz可以用更新版试一下吗
> 
> ```
> curl -fLO https://raw.githubusercontent.com/bohanyang/debi/force-lowmem/debi.sh && chmod a+rx debi.sh
> ```
> 
> 添加这个参数
> 
> ```
> --force-lowmem 1
> ```

本人384M机器DD Debian11，旧脚本与楼主相同问题，新脚本完美DD。
顺便想问下这个参数的 0 应该是相当于不开，1和2的区别是？2更极端吗？
我1能D过，是不是就不需要试试2了

**Comment by bohanyang** [comment]
是的，不需要。

默认情况下，
大概 780M 以上：关闭低内存模式（即为0）
780M 以下 460M 以上：低内存模式 1（可以自动安装，不会出现楼主截图的问题）
460M 以下 350M 以上：低内存模式 2（无法自动安装，需要手工加载模块，也就是出现楼主截图的问题）
350M 以下：内存过小无法运行

你 384M 内存是自动进入低内存模式 2 的，所以出现了以上问题。
添加 `--force-lowmem 1` 是强制设置为低内存模式 1，
也就是默认 460M 以上内存才能进入的模式，所以可以自动安装。

你设成 2 和没设是一样的。
