### ISSUE TITLE
甲骨文arm,dd后使用一段时间连不上vps

### ISSUE THREAD

**Issue by nooblikejagger** [bohanyang/debi#48]
![image](https://user-images.githubusercontent.com/58977259/148533555-4e9e9946-73c7-4acb-9d50-063157f312c4.png)
一直弹这个密码框, 没有改过密码,设置都没有动过
另一台dd过的amd的机器也有这个问题

**Comment by bohanyang** [comment]
密码框输入密码不行吗

**Comment by nooblikejagger** [comment]
> 

输入root会一直弹这个框 连不上vps
