### ISSUE TITLE
Not fully unattended

### ISSUE THREAD

**Issue by romanrm** [bohanyang/debi#5]
Hello,

I expected it would install everything on its own after a reboot. But after a long wait, I finally had to obtain VNC connection to the system, and saw that the Debian installer just sits there on the screen asking to specify the root password. After doing that, it asked me to also set up a user account.

The command line that I used was:

./debi.sh --ip 10.0.0.2 --netmask 255.255.255.0 --gateway 10.0.0.1 --no-user --password MySuperPassword --eth --force-efi-extra-removable

Expected that to specify the password for 'root', and not create the regular user account. If that's a wrong expectation, a warning should be printed, or some better way of handling this would be great.

**Comment by bohanyang** [comment]
You should not specify --no-user if you want fully unattended install. You should use --user root instead

**Comment by bohanyang** [comment]
--no-user means not generate user account related settings to preseed, i.e. manually proceed account setup in VNC

**Comment by bohanyang** [comment]
Naming is difficult. I've clearified the options in the new README. I'll close the issue for now. Thanks for your contribution.
