### ISSUE TITLE
dd  oracel vm 出错

### ISSUE THREAD

**Issue by chenli118** [bohanyang/debi#50]
7 blocks
GRUB_DEFAULT=debi
GRUB_TIMEOUT=5
GRUB_TIMEOUT_STYLE=menu
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.14.0-1.el7.elrepo.x86_64
Found initrd image: /boot/initramfs-5.14.0-1.el7.elrepo.x86_64.img
Found linux image: /boot/vmlinuz-5.4.17-2136.302.7.2.2.el7uek.x86_64
Found initrd image: /boot/initramfs-5.4.17-2136.302.7.2.2.el7uek.x86_64.img
Found linux image: /boot/vmlinuz-5.4.17-2102.204.4.4.el7uek.x86_64
Found initrd image: /boot/initramfs-5.4.17-2102.204.4.4.el7uek.x86_64.img
Found linux image: /boot/vmlinuz-0-rescue-9223233a5193441ea7466eac736e75b8
Found initrd image: /boot/initramfs-0-rescue-9223233a5193441ea7466eac736e75b8.img
Found linux image: /boot/vmlinuz-0-rescue-0af0ea5eb321434a87de66e6add68154
Found initrd image: /boot/initramfs-0-rescue-0af0ea5eb321434a87de66e6add68154.img
done
./debi.sh: line 803: grub-mkrelpath: command not found

**Comment by bohanyang** [comment]
你的原系统是？Oracle Linux的话暂不支持。
