### ISSUE TITLE
EFI 仅为 100M 在某些情况下太小

### ISSUE THREAD

**Issue by betaxab** [bohanyang/debi#53]
希望可以支持自定义 EFI 分区的大小，100M 在某些使用场景下太小了，不经意间可能就满了。

**Comment by bohanyang** [comment]
比如？什么场景？

**Comment by betaxab** [comment]
proxmox。然后 EFI 总是会爆。

106 数值我不知道怎么计算的，只知道

538 = 1048576 扇区 = 512MB
1050 = 2048000 扇区 = 1000M
1075 = 2097152 扇区 = 1GB

数学不好，搞得我头晕死了。

**Comment by bohanyang** [comment]
不是你数学不好，我也没搞清楚 Debian 是怎么转换的

**Comment by bohanyang** [comment]
你其实可以安装时进 VNC 或者 SSH console 手动分区

**Comment by betaxab** [comment]
哈哈，这个我明白，只不过如果说有个参数的话能方便一点点。通常情况我会把它设置成 512MB。

参考：
https://www.rodsbooks.com/efi-bootloaders/principles.html
https://wiki.archlinux.org/title/EFI_system_partition_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)

**Comment by bohanyang** [comment]
已填加
