### ISSUE TITLE
想问下大佬有支持 LUKS 加密的打算吗？

### ISSUE THREAD

**Issue by tonyzhou777** [bohanyang/debi#55]
如题

除了一些云大厂，Oneman 的 VPS 感觉还是全盘加密安全一点。如果能在重装时自动加密，那将方便很多。

请问有重装时添加 LUKS 的打算吗？

谢谢。

**Comment by bohanyang** [comment]
使用 `--no-part` 参数，然后可在 VNC 或 SSH network console 手动分区，
可以选择 Debian 安装程序自带的全盘加密选项，
因为要手动输入加密密码，所以没有办法全自动

**Comment by tonyzhou777** [comment]
明白了，感谢
