### ISSUE TITLE
reboot后无法连接

### ISSUE THREAD

**Issue by fefz** [bohanyang/debi#59]
使用VNC连接后，ping信息显示network unreachable
使用ip a看到网卡在，但是没有DHCP信息
报错如
<img width="754" alt="截屏2022-07-11 22 45 53" src="https://user-images.githubusercontent.com/16323430/178291881-fda878a8-a106-4d2b-8e47-b9202d106e5e.png">
<img width="761" alt="截屏2022-07-11 22 45 38" src="https://user-images.githubusercontent.com/16323430/178291909-a9c6bca2-bc82-4087-9b8c-b1dbc34caa3d.png">
下

**Comment by fmbfmbhh** [comment]
debian11的网络在甲骨文上有些问题，需要手动执行dhcp获取IP
`dhclient ens3`

**Comment by bohanyang** [comment]
不知道你用了什么命令，
默认装好之后不会有 iptables 的，
当然也没有 /etc/network/if-pre-up.d/iptables

我前几天在甲骨文 ARM 上试过没问题
