### ISSUE TITLE
大佬  甲骨文 arm 纯ipv6 没有v4，如果使用此脚本

### ISSUE THREAD

**Issue by pengkaiwei** [bohanyang/debi#6]
大佬  甲骨文 arm 纯ipv6 没有v4，如果使用此脚本

指定--ip 
然后指定dns，么

比如下面这样

sudo ./debi.sh --architecture arm64 --ip xxxx:c022:8002:xxxx::xxxx --dns 2a03:7900:2:0:31:3:104:161 --user root --password password

**Comment by bohanyang** [comment]
是的，纯 IPv6 的机器的话，需要手动指定 IP 及 CIDR，没记错的话甲骨文子网是 /64 的，所以是 --ip xxxx:c022:8002:xxxx::xxxx/64 。

DNS 的话默认会用 Google 的 v6 DNS，当然也可以自己指定。

甲骨文纯 v6 我还没试过，Scaleway 的纯 v6 机器我试过是 OK 的。

**Comment by bohanyang** [comment]
已在 Wiki 中更新 [教程](https://github.com/bohanyang/debi/wiki/%E7%94%B2%E9%AA%A8%E6%96%87%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%BA%AF-IPv6-%E7%BD%91%E7%BB%9C%EF%BC%88%E6%97%A0%E5%85%AC%E7%BD%91-IPv4%EF%BC%89%E4%B8%8B%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95)，可以试一下里面的命令吗？我试过是 OK 的，你看看有没有问题

**Comment by pengkaiwei** [comment]
> 已在 Wiki 中更新 [教程](https://github.com/bohanyang/debi/wiki/%E7%94%B2%E9%AA%A8%E6%96%87%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%BA%AF-IPv6-%E7%BD%91%E7%BB%9C%EF%BC%88%E6%97%A0%E5%85%AC%E7%BD%91-IPv4%EF%BC%89%E4%B8%8B%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95)，可以试一下里面的命令吗？我试过是 OK 的，你看看有没有问题

好的测试中
sudo ./debi.sh --architecture arm64 --ip xxxx:c022:8002:xxxx::xxxx/64 --gateway none --user root --password password

**Comment by pengkaiwei** [comment]
> 已在 Wiki 中更新 [教程](https://github.com/bohanyang/debi/wiki/%E7%94%B2%E9%AA%A8%E6%96%87%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%BA%AF-IPv6-%E7%BD%91%E7%BB%9C%EF%BC%88%E6%97%A0%E5%85%AC%E7%BD%91-IPv4%EF%BC%89%E4%B8%8B%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95)，可以试一下里面的命令吗？我试过是 OK 的，你看看有没有问题

测试成功，dd完后可以直接连上原来的v6 ssh。 不需要重新配置v6，谢谢大佬！
