### ISSUE TITLE
甲骨文的AMD CentOS 7.9 无法DD成Debian系统

### ISSUE THREAD

**Issue by AndersonGhost** [bohanyang/debi#61]
大佬，您好！如题所述，使用了您的脚本DD后，系统还是重启到原来的系统。
请问甲骨文的CentOS 7.9 如何DD成Debian系统？
请指教~  感谢！！

**Comment by bohanyang** [comment]
甲骨文请使用 Ubuntu 安装

**Comment by AndersonGhost** [comment]
现在的问题是：不能进甲骨文网页端的控制台了，只能通过ssh连接这台机器，无法将这台机器重置为Ubuntu。

**Comment by AndersonGhost** [comment]
> 甲骨文请使用 Ubuntu 安装

现在的问题是：不能进甲骨文网页端的控制台了，只能通过ssh连接这台机器，无法将这台机器重置为Ubuntu。
