### ISSUE TITLE
不能用lvm好像

### ISSUE THREAD

**Issue by allcdn** [bohanyang/debi#62]
![image](https://user-images.githubusercontent.com/70009473/184525818-e1a21f65-ebe3-4486-b683-4c9c3b8e0199.png)

**Comment by allcdn** [comment]
![image](https://user-images.githubusercontent.com/70009473/184525845-4839ae04-fe77-4a9d-aa7f-e70869779459.png)
用lvm创建分区后没有根目录

**Comment by bohanyang** [comment]
你的命令是什么

**Comment by allcdn** [comment]
sudo ./debi.sh --cdn --network-console --no-disk-partitioning --ip xxxx --netmask 255.255.255.192 --gateway xxx --ethx --user root --password xxxx --dns '1.1.1.1 8.8.8.8' --version 11 --timezone Asia/Shanghai

**Comment by bohanyang** [comment]
几乎相同的命令试过了，没问题呀
<img width="827" alt="image" src="https://user-images.githubusercontent.com/8384161/184527567-5a1f031b-1d6f-4e98-a35e-1867898d4776.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/8384161/184527579-be046ffa-1c4b-485b-a898-20cd3fb47297.png">

**Comment by allcdn** [comment]
你是vnc进去的吗？
我vnc进去没有问题
用installer用户进去就有问题了

**Comment by bohanyang** [comment]
vnc 和 ssh installer 都试了没问题
截图是 ssh installer 的

**Comment by allcdn** [comment]
installer用户有时候正常，有时候就会出现那个

**Comment by allcdn** [comment]
要不我把我服务器给你试试

**Comment by bohanyang** [comment]
tg `@brentybh`

**Comment by allcdn** [comment]
是不是我进 ssh installer进的太早了？

**Comment by bohanyang** [comment]
可能吧，还没加载完
