### ISSUE TITLE
请问可以同时设置ipv4和ipv6吗?

### ISSUE THREAD

**Issue by wxnode** [bohanyang/debi#69]
liteserver的vps,我重装后发现无法连接,登录vnc查看发现是无法dhcp获取ip.
我就手动指定了ipv4,现在是可以连接了,但是ipv6的不知道怎么指定,请问可以同时指定吗?

**Comment by bohanyang** [comment]
安装时不能指定两个，只能指定 IPv4 或 v6
需要安装之后再自行配置。
