### ISSUE TITLE
Oracle Cloud 安装完成后重启黑屏

### ISSUE THREAD

**Issue by p0we7** [bohanyang/debi#7]
进入到 VNC 后， 尝试过正常模式和 recovery 模式均为黑屏， ssh 无法连接上。

我看到安装日志上面是 5.x 的内核，但是 grub 启动界面显示的是 4.x 的内核。

**Comment by bohanyang** [comment]
Buster 默认只有 4.x 的内核。你有用 cloud kernel 吗？cloud kernel 在 UEFI 机器（比如 Oracle 或者 Azure 第2代）下就会 VNC 黑屏，但如果网络正常 SSH 也应该是正常的，系统也应该是没问题的

**Comment by p0we7** [comment]
是用 cloud kernel 的， SSH 一直超时在 VNC 可以 ctlr + alt + del 重启。

**Comment by bohanyang** [comment]
Cloud kernel 在 UEFI 机器下 VNC 黑屏我也尝试过很多办法都没解决，毕竟大厂（比如 Azure）默认模板也是一样的黑屏。系统应该是正常的，可能是网络配置不对吧

**Comment by p0we7** [comment]
貌似无解 ，只能删了重来。
