### ISSUE TITLE
daily-images 12号开始arm64目录里就没有netboot文件夹了 导致下载文件失败

### ISSUE THREAD

**Issue by ThreeSourLemon** [bohanyang/debi#70]
daily-images 12号开始arm64目录里就没有netboot了 导致下载文件失败
不清楚什么时候才恢复
https://d-i.debian.org/daily-images/arm64/daily/netboot/debian-installer/arm64/linux
Resolving d-i.debian.org (d-i.debian.org)... 2603:400a:ffff:bb8::801f:3e, 2001:67c:2564:a119::77, 2001:4f8:1:c::15, ...
Connecting to d-i.debian.org (d-i.debian.org)|2603:400a:ffff:bb8::801f:3e|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-15 13:45:45 ERROR 404: Not Found.

**Comment by bohanyang** [comment]
奇了怪了
不会是以后都没有了吧

**Comment by ThreeSourLemon** [comment]
> 
又去看了下 里面有个build netboot  log好像从12号开始就一直编译失败
之前是成功的  
应该给他们反馈下就好了
就是不知道应该怎么给他们反馈😀

**Comment by bohanyang** [comment]
应该也是知道的……
daily 就算是开发版吧
平常没必要用

**Comment by bohanyang** [comment]
好像已经好了
