### ISSUE TITLE
无法正常DD

### ISSUE THREAD

**Issue by fengguowudi** [bohanyang/debi#71]
![image](https://user-images.githubusercontent.com/55879152/209458287-271e2006-34a9-41ea-85da-aaede58247b5.png)

**Comment by fengguowudi** [comment]
![image](https://user-images.githubusercontent.com/55879152/209458314-a5a9ece7-6057-4236-b37c-0f2b29ed27ab.png)

**Comment by fengguowudi** [comment]
机器配置：

**Comment by bohanyang** [comment]
请提供详细信息。

**Comment by fengguowudi** [comment]
> 请提供详细信息。

请问还需要什么信息

**Comment by fengguowudi** [comment]
重装前系统为Ubuntu 22

**Comment by fengguowudi** [comment]
服务器位于美国

**Comment by fengguowudi** [comment]
sudo ./debi.sh --network-console --timezone Asia/Shanghai --ntp time.windows.com --ethx --user root --password xxxxxxx --ip xxxx --gateway xxxxxxx --netmask 255.255.255.0 --aws

**Comment by fengguowudi** [comment]
使用以下参数运行

**Comment by bohanyang** [comment]
看下来我也不知道为什么。
说是磁盘空间不够，虽然11G应该是够的。

**Comment by fengguowudi** [comment]
> 看下来我也不知道为什么。 说是磁盘空间不够，虽然11G应该是够的。

有联系方式吗？我机子可以直接给你调试

**Comment by fengguowudi** [comment]
> 看下来我也不知道为什么。 说是磁盘空间不够，虽然11G应该是够的。

或者我在这里直接给你？

**Comment by bohanyang** [comment]
单独服务的话，需要付费。
可以联系 Telegram `@brentybh`。
