### ISSUE TITLE
控制台连接

### ISSUE THREAD

**Issue by peterzh1** [bohanyang/debi#73]
重装系统后，甲骨文官方网页无法创建控制台连接，这个有办法解决吗？

**Comment by bohanyang** [comment]
感谢您提出这个问题。关于甲骨文官方网页无法创建控制台连接的问题，可能是由于 Oracle Cloud 的一些限制或配置问题造成的，而与我的脚本无关。很遗憾，我并没有能够解决这个问题的方法。

我建议您在 Oracle Cloud 的官方文档或支持论坛中寻求更多帮助。如果您发现与我的脚本有关的任何问题，请随时告诉我。感谢您对我的脚本的使用和支持！

**Comment by Mr3h1v** [comment]
Oracle的控制台连接是通过串口

dd成功后的系统 /etc/default/grub文件添加以下几行

GRUB_TERMINAL_INPUT="console serial" 
GRUB_TERMINAL_OUTPUT="gfxterm serial" 
GRUB_SERIAL_COMMAND="serial --unit=0 --speed=115200" 
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} console=tty0 console=ttyS0,115200"

执行 sudo update-grub 更新引导项
重启系统后生效
