### ISSUE TITLE
甲骨文 无法获取ipv6

### ISSUE THREAD

**Issue by 1621391916** [bohanyang/debi#74]
系统为Debian11
systemctl stop networking && systemctl stop ifup@eth0 && systemctl start systemd-networkd
这一步之后ssh并没有断连。网卡名字换成了enp0s3
curl支持ipv6的网址时可以看到解析到了v6的地址，但是就是连不上
![image](https://user-images.githubusercontent.com/42343279/224459408-5905e539-4edc-4887-bc8f-8fbbb42c1af2.png)

**Comment by bohanyang** [comment]
感谢您联系我们并分享您在使用脚本过程中的问题。我们很高兴看到社区成员互相帮助，但需要说明的是，我们并非您的技术支持团队。

根据您提供的信息，我们建议您检查是否已在 /etc/systemd/network 中为您的网络接口添加了适当的配置文件，以确保网络配置正确。如果您需要进一步的帮助，请联系您的技术支持团队或者在适当的技术支持论坛上提问。

您还可以参考以下内容：#46

感谢您对我们的开源项目的关注和支持！
