### ISSUE TITLE
Oracle IPv6 problem

### ISSUE THREAD

**Issue by davidsarkany** [bohanyang/debi#88]
I installed Debian to my Oracle ARM VM and followed this [guide](https://github.com/bohanyang/debi/wiki/%E7%94%B2%E9%AA%A8%E6%96%87%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%87%AA%E5%8A%A8%E8%8E%B7%E5%8F%96-IPv6).

ip a output:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:00:17:00:aa:2b brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 10.0.0.191/24 brd 10.0.0.255 scope global dynamic eth0
       valid_lft 86388sec preferred_lft 86388sec
    inet6 fe80::17ff:fe00:aa2b/64 scope link 
       valid_lft forever preferred_lft forever
```

I found a workaround. I manually installed the dhclient and run the command from the terminal.
`dhclient -6 eth0`

How can I solve this issue?

**Comment by bohanyang** [comment]
It's weird. My current network file is:
```
[Match]
Name = eth0

[Network]
DHCP = ipv4
NTP = 169.254.169.254

[DHCPv4]
UseHostname = false
```

It's working at least for me.

Maybe you don't have to use systemd-networkd, but just stick to to old ifup & /etc/interfaces

You can refer to https://github.com/bohanyang/debi/discussions/81

**Comment by bohanyang** [comment]
> I manually installed the dhclient

Usually dhclient should be pre-installed and it's used by ifupdown & /etc/interfaces

In my guide, I purged it since systemd-networkd can do DHCP by itself.

**Comment by davidsarkany** [comment]
I did a clean Debian 12 install.

Create a new file /etc/systemd/network/10-eth0.network with the following content.

```
[Match]
Name = eth0

[Network]
DHCP = ipv4
NTP = 169.254.169.254

[DHCPv4]
UseHostname = false
```

Run this command:
`systemctl stop networking && systemctl stop ifup@eth0 && systemctl start systemd-networkd`

then this:
```
systemctl enable systemd-networkd
apt purge -y --auto-remove ifupdown isc-dhcp-client
```
After the reboot I don't have IPv6 connection

**Comment by zijiren233** [comment]
seam, kernel version: 6.1.0-9-amd64, use bbr fq_pie

**Comment by bohanyang** [comment]
All IPv6 in my Oracle VMs are down suddenly.

**Comment by davidsarkany** [comment]
> All IPv6 in my Oracle VMs are down suddenly.

My config still works.

**Comment by bohanyang** [comment]
Yeah, so maybe there's an issue of Oracle's DHCP / IPv6 auto config.
