### ISSUE TITLE
昨天DD全失败了

### ISSUE THREAD

**Issue by imoldchen** [bohanyang/debi#9]
大概来回折腾了10多次，不同的几个区的arm重启都进不去了，前天都还能用。。。

**Comment by bohanyang** [comment]
你光这么说我也没办法知道原因啊，运行的命令，环境呢

**Comment by imoldchen** [comment]
开的 Oracle arm，默认的Ubuntu20，昨天之前DD没有一次失败，从昨天开始出现DD失败后，以为是自己参数弄错，断断续续尝试了5个区，重开了10几次，再没成功过，从最精简的到复杂的参数差不多都试过

sudo ./debi.sh --architecture arm64 --network-console --ethx --user root --password xxxxxxx

sudo ./debi.sh --cdn --architecture arm64 --ethx --user root --password xxxxxxx

sudo ./debi.sh --network-console --architecture arm64 --filesystem ext4 --ethx --bbr --efi --mirror-host ftp.xx.debian.org --mirror-protocol http --suite buster --cloud-kernel --user root --password xxxxx --ip 10.0.0.xx --gateway 10.0.0.1 --netmask 255.255.255.0 --hostname xxxx

**Comment by bohanyang** [comment]
执行命令并重启后可以 ping 通吗？VNC有显示什么吗

**Comment by imoldchen** [comment]
arm 的vnc只能看，就是执行重启，在选择内核引导界面，看到默认选择是 Install，再之后就没显示了，ping不通，控制台参数加上之后，可以看到卡在无网络报错，再过一会就连不上了。

**Comment by bohanyang** [comment]
那就是网络配置不对吧。
1. 机器有没有绑定公网 IP
2. 是纯 IPv6 还是有 IPv4 的

**Comment by bohanyang** [comment]
麻烦确认以下几点：
1. 创建一台全新机器（选择默认 Ubuntu 20 系统）后，公网访问（wget 及 ssh 等）正常
2. 然后使用 README 那个命令（不带 `--architecture arm64`）

然后重启后随时尝试 ping 或者 ssh 看看网络通不通

**Comment by imoldchen** [comment]
公网ipv4是获取了的，因为后面要用ifconfig看网络信息，这个Ubuntu20.04默认是没有的，我都执行过一遍apt updete，再 apt intall net-tools，我现在没再DD系统了，有几个已经脚本都开不出来了，开出来的自己安装过环境，网络都是通的。

**Comment by bohanyang** [comment]
其实看网络信息可以用 ip 命令（`ip addr` `ip route` 等）

**Comment by bohanyang** [comment]
一般来说 DHCP 自动配置公网 IPv4 都没有问题的

**Comment by imoldchen** [comment]
我还是没忍住，再弄了一次，这次我不去掉了一个参数  --ethx，进入控制台它停在一个步骤需要选择，我按确定看着它自动安装，提示完成并重启，再次完美失联。

**Comment by bohanyang** [comment]
有 telegram 吗，加我 https://t.me/brentybh
就不信了怎么会失联

**Comment by bohanyang** [comment]
1. 不要用 cloud kernel
2. 失联之后 VNC 上有显示吗

**Comment by imoldchen** [comment]
1.这次安装出来指定IP网关这些，没用多余的参数，没用 cloud kernel
2，失联之后没显示

**Comment by imoldchen** [comment]
![屏幕截图 2021-06-21 133656.jpg](https://i.loli.net/2021/06/21/xKwYPJuIeOmNrnp.jpg)
就是卡在这个界面，只能选第一项，选其他的直接没响应了。
用的命令 
sudo ./debi.sh --network-console --architecture arm64 --user root --password xxxxxx --ip 10.0.0.13 --gateway 10.0.0.1 --netmask 255.255.255.0

**Comment by bohanyang** [comment]
出这个页面就是正常的。你用的命令属于全自动安装（没有指定手动安装的相关选项），所以安装已经在后台（就是VNC那个屏幕上）进行了！

全自动的话不要在这个界面回车进入任何选项。

可以按 Ctrl-A 然后松手再按 4 监控安装日志。

**Comment by NLcoin** [comment]
finish-install: dpkg-divert: warning: diverting file '/sbin/start-stop-daemon' from an Essential package with rename is dangerous, use --no-rename
有一个这个错误

**Comment by bohanyang** [comment]
已确认问题存在，尝试查找原因中

**Comment by bohanyang** [comment]
不是网络问题，直接没启动成功，而且也不是引导问题，好像内核直接崩了

**Comment by bohanyang** [comment]
安装 backports 的 5.10.0 内核和`flash-kernel`似乎可以成功（虽然不知道具体原因），
@imoldchen 可以尝试一下加上这个参数看看能否成功？
`--install 'ca-certificates libpam-systemd linux-image-5.10.0-0.bpo.7-arm64 flash-kernel'`

**Comment by bohanyang** [comment]
@imoldchen 脚本已更新，请尝试加上 `--bpo-kernel` 参数看看能否成功？

**Comment by imoldchen** [comment]
加不加这个参数都成功了，感谢。

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/135722257-49a5f870-e59f-4c8d-bf38-a72011660c5e.png)
DigitalOcean直接网络配置错误
`sudo ./debi.sh --network-console --version 11 --user sekibetu --password <新系统用户密码> --authorized-keys-url https://github.com/SekiBetu.keys --timezone Asia/Shanghai --architecture amd64
`

**Comment by bohanyang** [comment]
digitalocean 没有 dhcp 了，要手动配置网络。

**Comment by SekiBetu** [comment]
> digitalocean 没有 dhcp 了，要手动配置网络。

https://www.cxthhhhh.com/Network-Reinstall-System-Modify

我用了这个脚本，也没让手动配置，不知道啥原理

**Comment by bohanyang** [comment]
像 moeclub 的脚本啥的会从当前系统配置里面获取静态 IP。
这功能我不是很想做，太hack了
（不同系统配置不同，可能有n个网卡，一个网卡n个IP，有公网有私网NAT，复杂度高bug就多）

用户也应该充分了解我这次重装后
系统只配置哪一个网卡，什么IP什么网关，公网直连还是私有IP NAT连公网。

一般VPS或云都有DHCP。如果只有一个公网用网卡直接DHCP自动配置就OK。

由于以上原因，我认为要不就用DHCP自动配置，要不就手动配置，这样兼顾
1.足够的便捷度 2.灵活性 3.代码少，复杂度低，出bug概率低
