### ISSUE TITLE
运行前不会检查 `cpio` 、`update-grub` 和 `grub2-mkconfig`是否安装

### ISSUE THREAD

**Issue by Glucy-2** [bohanyang/debi#92]
碰到了个极其精简的系统要重装，运行一半弹 `./debi.sh: 791: cpio: not found` 还有 `Error: Could not find "update-grub" or "grub2-mkconfig" command.` ，建议运行前检查依赖

**Comment by bohanyang** [comment]
重新运行即可，中断也不影响的
想取消删除 sudo rm -rf debi.sh /etc/default/grub.d/zz-debi.cfg /boot/debian-* && { sudo update-grub || sudo grub2-mkconfig -o /boot/grub2/grub.cfg; }
