### ISSUE TITLE
通过--install 参数选择安装iperf3，会在安装过程中提示是否默认启动

### ISSUE THREAD

**Issue by lifetyper** [bohanyang/debi#93]
如题，如果通过--install 参数选择安装iperf3，会在安装过程中提示是否默认启动iperf3，如果没有在vnc界面操作，就会一直卡在这个询问界面上，是否有办法跳过这个询问呢？

**Comment by bohanyang** [comment]
```
kernel_params="$kernel_params lowmem/low=1"

[ -n "$force_lowmem" ] && kernel_params="$kernel_params lowmem=+$force_lowmem"

initrd="$installer_directory/initrd.gz"
[ "$firmware" = true ] && initrd="$initrd $installer_directory/firmware.cpio.gz"

$save_grub_cfg 1>&2 << EOF
menuentry 'Debian Installer' --id debi {
    insmod part_msdos
    insmod part_gpt
    insmod ext2
    insmod xfs
    insmod btrfs
    linux $installer_directory/linux$kernel_params
    initrd $initrd
}
EOF
```
你修改 debi.sh 在 kernel_params 后面加 `DEBIAN_FRONTEND=noninteractive` 试试呢
（我没试过）

```
kernel_params="$kernel_params lowmem/low=1 DEBIAN_FRONTEND=noninteractive"

```

**Comment by lifetyper** [comment]
`linux $installer_directory/linux$kernel_params DEBIAN_FRONTEND=noninteractive`
是这样写吗？这样写了以后重启VNC直接灰屏没法显示了，再重启就进了grub rescue

**Comment by bohanyang** [comment]
额

或者在 748 行前面加上 `echo "d-i iperf3/start_daemon boolean false" | $save_preseed`

https://github.com/bohanyang/debi/blob/70168f8d46af2fc48c24e3819deb76ffad9884e0/debi.sh#L738-L748

**Comment by lifetyper** [comment]
> echo "d-i iperf3/start_daemon boolean false" | $save_preseed

非常感谢，这样写确实不会跳出提示了。

但是否有更自动化的方法来处理这个问题呢，毕竟这个是针对iperf3特例的写法，而且具体哪些程序安装的时候会跳出提醒，也不知道有什么标准来预判。
对于安装的程序全部都像iperf3这样加入/start_daemon boolean false 选项是否可行呢？还是有什么通配选项可用？

**Comment by lifetyper** [comment]
> echo "d-i iperf3/start_daemon boolean false" | $save_preseed

非常感谢，这样写确实不会跳出提示了。

但是否有更自动化的方法来处理这个问题呢，毕竟这个是针对iperf3特例的写法，而且具体哪些程序安装的时候会跳出提醒，也不知道有什么标准来预判。
对于安装的程序全部都像iperf3这样加入/start_daemon boolean false 选项是否可行呢？还是有什么通配选项可用？

再次感谢。

**Comment by bohanyang** [comment]
暂时没发现好办法
试了下 `d-i debconf/frontend select Noninteractive` 并没有用
