### ISSUE TITLE
重启成功后无法登录

### ISSUE THREAD

**Issue by suikaremilia** [bohanyang/debi#95]
`./debi.sh --cdn --network-console --ethx --bbr --user root --password oJKwJlG\M+0TN#sS`
用以上命令重装成功了，但无论如何都ssh不上去，是因为密码有特殊字符的关系么？有是么解决的办法么？
谢谢！

**Comment by leitbogioro** [comment]
用我脚本试试：
https://github.com/leitbogioro/Tools
中文文档：
https://www.nodeseek.com/post-9383-1
密码原则上不建议预先设置，有问题去我github主页或论坛提反馈

**Comment by bohanyang** [comment]
你没加引号
