### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Stage4000** [bohanyang/debi#96]
Hi there, I want to thank you for this script. I have used it multiple times today on an OCI machine with 0 issues.

I was curious how hard it would be to add Ubuntu to the script. Is there some way I can do this with the provided flags already?

**Comment by bohanyang** [comment]
Thanks for your support!

Unfortunately, although Ubuntu is based on Debian, it seems that they haven't updated their [debian-installer](http://archive.ubuntu.com/ubuntu/dists/jammy/main/installer-amd64/) for many years.

Actually I had tried to add Ubuntu support to the script, but I found that Ubuntu's installer is very buggy and doesn't support many useful parameters.
