### ISSUE TITLE
请问GCP应该如何设置？

### ISSUE THREAD

**Issue by lsyyktv** [bohanyang/debi#98]
curl -fLO https://raw.githubusercontent.com/bohanyang/debi/master/debi.sh && chmod a+rx debi.sh

sudo ./debi.sh --cdn --network-console --ethx --gateway 10.140.0.1 --ip 10.140.0.11 --version 10 --timezone Asia/Shanghai --bbr --user root --password 12345678

使用上面两条命令之后就失联了，不知道是哪里设置有问题

**Comment by bohanyang** [comment]
--ip 没加 CIDR

**Comment by lsyyktv** [comment]
> --ip 没加 CIDR

好的，我再试试吧，我以为已经指定了具体的内网IP地址，就不需要加CIDR了？
